USE CUSTOMER_SHOPPING_DATA;
SELECT * FROM mytable;
-- Q1) what is the total revenue generated by male vs female customers 
SELECT gender , SUM(purchase_amount) AS revenue
FROM mytable
GROUP BY gender;

-- Q2) which customer uses discount still spend more than avarage purchase amount
SELECT customer_id, purchase_amount
FROM mytable 
WHERE discount_applied = 'YES' AND  purchase_amount >= (SELECT AVG(purchase_amount) FROM mytable);

-- Q3) what are the top five product with highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating),2) FROM mytable GROUP BY item_purchased ORDER BY AVG(review_rating) DESC LIMIT 5;

-- 4) compare average purchase amount between standard and express shipping
SELECT shipping_type, AVG(purchase_amount) FROM mytable WHERE shipping_type IN('Express', 'Standard') GROUP BY shipping_type ;

-- Q5) do subscriber customer spend more ? compare the average spend and total revenue between subcriber and non subscribers
SELECT  subscription_status ,COUNT(customer_id), ROUND(AVG(purchase_amount),2) AS AVERAGE_SPEND, SUM(purchase_amount) FROM mytable GROUP BY subscription_status;

-- Q6) WHICH 5 PRODUCTS HAS HIGHEST PURCHASE WITH DISCOUNT APPLIED ?
SELECT item_purchased ,
ROUND(100 * SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END)/ COUNT(*), 2) AS discount_rate
FROM mytable
GROUP BY item_purchased 
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7) SEGMENT CUSTOMER INTO NEW, RETRUNING AND LOYAL BASED ON NUMBERS OF PREVIUOS PURCHASE AND SHOW THE COUNT OF EACH SEGMENT
with customer_type as (
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'NEW'
    WHEN previous_purchases  BETWEEN 2 AND 10 THEN 'RETUNING'
    ELSE 'LOYAL'
    END AS customer_segment
from mytable

)
select customer_segment , count(*) as number_of_customers
from customer_type
group by customer_segment;

-- Q8) WHAT ARE THE TOP 3 MOST PURCHASE PRODUCT WITHIN EACH CATEGORY 

with item_counts as(
select category, 
item_purchased,
count(customer_id) as total_count,
row_number() over(partition by category order by count(customer_id) desc ) as item_rank
from mytable
group by category, item_purchased

)
select item_rank, category, item_purchased, total_count
from item_counts 
where item_rank <= 3;
 
 -- Q9) are customers who are repeated buyers ( more than 5 prchases ) also lkely to subscribe
 select subscription_status,
 COUNT(customer_id) as repeatde_buyers
 from mytable
 where previous_purchases > 5
 group by subscription_status;
 
 -- Q10) revenue by age group
 select age_group , sum(purchase_amount) as tatal_revenue, avg(purchase_amount)  as avg_purchase from mytable group by age_group order by tatal_revenue desc;
 
 
 



